
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.35"
  config.hostsupdater.aliases = ["development.local"]

  config.vm.provision "chef_solo" do |chef|
      chef.add_recipe "elasticsearch::default"
    end
end
